### ISSUE TITLE
Device Network Id? And "create a new device using this handler"

### ISSUE THREAD

**Issue by gradyhouston** [xtreme22886/PS4-Waker-SmartThings-Device-Handler#1]
Hello! 

Trying to get this working. I have everything working up until the "create a new device using this handler". When I go to create a new device, I don't have the option to use this handler I just made. It wants me to input everything manually, in which case I don't have a Device Network Id and am unsure of the "Type" to use. When I put in anything (tried 0) and it reads as "unknown" in the SmartThings app. I'm not sure how to tie your code to the "new device".

**Comment by xtreme22886** [comment]
Hi @gradyhouston,

So sorry about the late reply. I don't recall being notified about this post so I never saw it till now. If you are still having troubles, then.

1. Did you make sure to 'Publish' the Device Handler?
2. Once published, head over to 'My Devices' and create a new device. You can name the device whatever you like (I've named mine "PS4 Control"). The network ID can be anything you like as well, it just has to be unique between all your devices (I used "ps000000001"). For the type, make sure to select "ps4-waker" which is usually at the bottom of the list (or towards the bottom). Lastly the version should be "Published".

That should be all that is required in the IDE. Once all that is done, you should be able to open up the SmartThings app and edit this device to input: Waker IP, Waker Port, PS4 IP and game IDs.

Let me know if you are still having troubles.
